### ISSUE TITLE
Cannot read property 'substr' of undefined

### ISSUE THREAD

**Issue by chrisgorgo** [vsoch/nidmviewer#9]
I'm getting an error with those two NIDM-Results 1.3.0 examples:
http://neurovault.org/collections/1404/fsl_ds005_sub-01.nidm
http://neurovault.org/collections/1404/fsl_ds005_group.nidm

Uncaught TypeError: Cannot read property 'substr' of undefined
papaya.volume.Volume.readURLs  @ papaya.js:399
papaya.viewer.Viewer.loadOverlay @ papaya.js:648
(anonymous function) @ fsl_ds005_sub-01.nidm:205

**Comment by vsoch** [comment]
That means that whatever variable is going into the viewer for the image is undefined. How are these data structures different from the working ones? It's hard to keep up to date / track of how this nidm standard is changing.

**Comment by chrisgorgo** [comment]
I know - feel the same way. Can you tell which variable is undefined and which query failed to pick it up?

I don't have any more insight into what change made those examples incompatible with the viewer. I got them from @cmaumet. Maybe she can shed some light.

**Comment by vsoch** [comment]
Sure, will take a look tomorrow or this weekend.

**Comment by cmaumet** [comment]
I could not reproduce the 'substr' error but I got both examples to work on my machine with #10. Those examples both have no supra-threshold voxels and I think this was causing the issue. Let me know if I can provide more info!
